### ISSUE TITLE
Expired discord link in readme

### ISSUE THREAD

**Issue by Mikooboy** [gabrielhamel/wg-mod#23]
Discord link is expired.

Also, is there a way to setup the development environment so that IntelliSense works?

I have not used rust before and I'm not sure if this tool sets up a whole project somewhere like visual studio does. I just opened the python file in the mod's folder and started editing that.

**Comment by gabrielhamel** [comment]
Oh sorry ! I have updated the invite link -> https://discord.gg/XGzqS5Sb9G

> Also, is there a way to setup the development environment so that IntelliSense works?

Yep I succeed to do that with Pycharm for Python. For the moment you can see interpreters paths to add via the command `wg-mod pycharm`

I started to write a tutorial for that.

> I have not used rust before and I'm not sure if this tool sets up a whole project somewhere like visual studio does

This is the main goal of this crate. (Work only for python mods)

Feel free to contact me on my discord servers
